# Generated by Django 4.1.2 on 2023-04-20 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500, null=True)),
                ('useremail', models.EmailField(max_length=100)),
                ('foto_perfil', models.ImageField(null=True, upload_to='main/imagens/perfil/')),
                ('foto_banner', models.ImageField(null=True, upload_to='main/imagens/banner/')),
                ('linkedin', models.URLField(null=True)),
                ('github', models.URLField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
