# Generated by Django 4.1.2 on 2023-04-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_banner',
            field=models.ImageField(null=True, upload_to='main/static/imagens/banner/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='main/static/imagens/perfil/'),
        ),
    ]
