# Generated by Django 4.1.2 on 2023-04-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_perfil_foto_banner_alter_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='descricao',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_banner',
            field=models.ImageField(null=True, upload_to='main/imagens/banner/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='main/imagens/perfil/'),
        ),
    ]
