# Generated by Django 4.2 on 2023-05-13 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coluna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('editavel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField()),
                ('prazo', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('publico', models.BooleanField(default=False)),
                ('convites_enviados', models.ManyToManyField(blank=True, related_name='convites_enviados', to=settings.AUTH_USER_MODEL)),
                ('convites_pendentes', models.ManyToManyField(blank=True, related_name='convites_pendentes', to=settings.AUTH_USER_MODEL)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_criados', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(blank=True, related_name='projetos_membros', to=settings.AUTH_USER_MODEL)),
                ('moderadores', models.ManyToManyField(blank=True, related_name='projetos_moderados', to=settings.AUTH_USER_MODEL)),
                ('solicitacoes_entrada', models.ManyToManyField(blank=True, related_name='solicitacoes_entrada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_coluna', to='Tables.coluna')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tables.projeto')),
            ],
        ),
        migrations.AddField(
            model_name='coluna',
            name='itens',
            field=models.ManyToManyField(related_name='colunas', to='Tables.item'),
        ),
        migrations.AddField(
            model_name='coluna',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='Tables.projeto'),
        ),
    ]
